plugins {
    id 'com.android.application'
}

android {
    namespace 'com.luccaa53mini'
    compileSdk 35

    defaultConfig {
        applicationId "com.luccaa53mini"
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName "1.03"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
        resValues false
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
}
